### PR TITLE
New Template

### PR DESCRIPTION
**Pull request by mtzeka**

### CODE REVIEW

**Comment by ppeble** [comment]
I like it! I have two questions:

1) Some of the colors between Post headers and headers within the content seems too close for me. I have a hard time immediately seeing when one post ends and another begins. Am I alone in this?

2) Are we going to display the entire posts? Or do we want to display part of them and make the user click through to read it in full? I think maybe I will be more okay with displaying everything if there is more delineation between the headers.

**Comment by mtzeka** [comment]
@ptrimble 

1) I'm trying to use the classic console color scheme and those two seem to be the best for headers. I decided to change the title to bigger, underlined font. Does that help?

2) I like the idea of not showing the entire post, however, that'll require us to manage a "snippet" version as well because if we truncate we may end up truncating a snippet of code. So I think it'd be simpler to just provide the entire post rather than manage two different posts (what if we make changes later on? Etc). I made the post headers smaller to help with the distinction.

**Comment by ppeble** [comment]
Okay, great, let me take a look later this evening and I'll let you know what I think.

**Comment by ppeble** [comment]
New design looks great! I would like @samsoir to provide final feedback.

**Comment by samsoir** [comment]
Homepage

Design is subjective… of course. For me less is always more.

I would remove the header underline and give the titles and other headers more whitespace padding. The teal and the blue colors I am also less of a fan of, but can live with. Black tie is definitely my style :)

I think that only links (or Call To Actions) should have any significant color or emphasis, outside of code markup.

Other than that I think this design is awesome! :+1:

**Comment by mtzeka** [comment]
@samsoir The black titles is a good idea -- I just changed those to black.

**Comment by ppeble** [comment]
@mtzeka @samsoir Looks good to me! I'm going to merge this in and the other initial posts and get this all up and running.

**Pull request merged**
